const videoElement = document.getElementById('input_video');
const canvasElement = document.getElementById('output_canvas');
const canvasCtx = canvasElement.getContext('2d');
const flapSpeedDisplay = document.getElementById('flap-speed-display');

// Game State
let isPlaying = false;
let gameOver = false;

let flapSpeed = 0; // Speed generated by player flapping
let playerDistance = 0; // Total distance traveled by player
let predatorDistance = -400; // Total distance traveled by predator (starts 400px behind)

let lastTime = performance.now();
const trackElement = document.getElementById('track');
const playerElement = document.getElementById('player');
const predatorElement = document.getElementById('predator');
const distanceDisplay = document.getElementById('distance');
const legsElement = document.querySelector('.legs');

let highScore = localStorage.getItem('flapToRunHighScore') || 0;
const highScoreDisplay = document.getElementById('high-score');
highScoreDisplay.innerText = highScore;

// Predator mechanics
let predatorBaseSpeed = 100; // Pixels per second
let predatorAcceleration = 5; // Pixels per second squared

let previousWristDiff = null;

function calculateFlapSpeed(landmarks) {
  // Extract wrists
  const leftWrist = landmarks[15];
  const rightWrist = landmarks[16];

  let currentFlapSpeed = 0;

  if (leftWrist && rightWrist && leftWrist.visibility > 0.5 && rightWrist.visibility > 0.5) {
    // Measure the vertical distance between wrists
    // This perfectly captures opposing motion: when one goes up and one goes down, this difference changes rapidly.
    // If they both go up or down together, the difference stays the same.
    const currentDiff = leftWrist.y - rightWrist.y;

    if (previousWristDiff !== null) {
      const delta = Math.abs(currentDiff - previousWristDiff);
      
      // Apply a deadzone to ignore small jitter/noise when stationary
      if (delta > 0.015) { 
        currentFlapSpeed = delta * 40000; 
      }
    }
    previousWristDiff = currentDiff;
  }
  
  // Exponential decay smoothing for the flap speed
  flapSpeed = flapSpeed * 0.9 + currentFlapSpeed * 0.1;
}

function onResults(results) {
  canvasCtx.save();
  canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
  
  // Draw video frame on canvas
  canvasCtx.drawImage(results.image, 0, 0, canvasElement.width, canvasElement.height);

  if (results.poseLandmarks) {
    // Hide non-arm landmarks so the face/legs aren't drawn
    const armIndices = [11, 12, 13, 14, 15, 16]; // Shoulders, Elbows, Wrists
    results.poseLandmarks.forEach((landmark, index) => {
      if (!armIndices.includes(index)) {
        landmark.visibility = 0;
      }
    });

    // Draw landmarks
    drawConnectors(canvasCtx, results.poseLandmarks, POSE_CONNECTIONS, {color: '#ff00ff', lineWidth: 4});
    drawLandmarks(canvasCtx, results.poseLandmarks, {color: '#39ff14', lineWidth: 2, radius: 4});

    // Calculate speed if game is active
    if (isPlaying) {
      calculateFlapSpeed(results.poseLandmarks);
      flapSpeedDisplay.innerText = Math.floor(flapSpeed);
    }
  }
  canvasCtx.restore();
}

const pose = new Pose({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
}});
pose.setOptions({
  modelComplexity: 1,
  smoothLandmarks: true,
  enableSegmentation: false,
  smoothSegmentation: false,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});
pose.onResults(onResults);

const camera = new Camera(videoElement, {
  onFrame: async () => {
    await pose.send({image: videoElement});
  },
  width: 320,
  height: 240
});
camera.start();

// Game Loop
function gameLoop(now) {
  if (!isPlaying) {
    lastTime = now;
    requestAnimationFrame(gameLoop);
    return;
  }

  const dt = (now - lastTime) / 1000; // Delta time in seconds
  lastTime = now;

  // 1. Update Player
  // Apply a base minimum speed or just flap speed
  let currentSpeed = flapSpeed;
  if (currentSpeed < 10) currentSpeed = 0; // Deadzone
  
  playerDistance += currentSpeed * dt;

  // 2. Update Predator
  // "Rubber-band" mechanic: the JOB matches 85% of your speed, plus a baseline hustle that grows over time.
  // This ensures it is always hot on your tail!
  let currentPredatorSpeed = 150 + (playerDistance * 0.02) + (currentSpeed * 0.85); 
  predatorDistance += currentPredatorSpeed * dt;

  // 3. Render
  // The player is stationary horizontally (centered). 
  // Track and predator move relative to player.
  const diff = playerDistance - predatorDistance;
  
  // Calculate window center
  const centerX = window.innerWidth / 2;
  
  // Predator visual position = center - diff
  const predatorLeft = centerX - diff;
  predatorElement.style.left = predatorLeft + "px";

  // Track scrolling
  trackElement.style.backgroundPositionX = -(playerDistance * 0.5) + "px";
  // Body background scrolling
  document.getElementById('game-container').style.backgroundPositionX = -(playerDistance * 0.2) + "px";

  // Distance display
  distanceDisplay.innerText = Math.floor(playerDistance / 100);

  // Animate player bobbing
  if (currentSpeed > 50) {
    playerElement.classList.add('player-run');
    legsElement.classList.add('running-legs');
  } else {
    playerElement.classList.remove('player-run');
    legsElement.classList.remove('running-legs');
  }

  // 4. Game Over Condition
  if (diff <= 0) {
    // Escaped failed, JOB caught you!
    isPlaying = false;
    gameOver = true;
    document.getElementById('game-over').classList.remove('hidden');
    
    let finalDist = Math.floor(playerDistance / 100);
    document.getElementById('final-distance').innerText = finalDist;
    
    if (finalDist > highScore) {
      highScore = finalDist;
      localStorage.setItem('flapToRunHighScore', highScore);
      highScoreDisplay.innerText = highScore;
    }
  }

  requestAnimationFrame(gameLoop);
}

// Start sequence
document.getElementById('start-btn').addEventListener('click', () => {
  document.getElementById('ui-overlay').classList.add('hidden');
  isPlaying = true;
  gameOver = false;
  playerDistance = 0;
  predatorDistance = -400; // Starts 400 pixels behind
  flapSpeed = 0;
  lastTime = performance.now();
});

document.getElementById('restart-btn').addEventListener('click', () => {
  document.getElementById('game-over').classList.add('hidden');
  document.getElementById('ui-overlay').classList.remove('hidden');
  
  // Reset initial visuals behind the UI
  playerDistance = 0;
  predatorDistance = -400;
  const diff = playerDistance - predatorDistance;
  const centerX = window.innerWidth / 2;
  predatorElement.style.left = (centerX - diff) + "px";
  trackElement.style.backgroundPositionX = "0px";
  document.getElementById('game-container').style.backgroundPositionX = "0px";
  distanceDisplay.innerText = "0";
  playerElement.classList.remove('player-run');
  legsElement.classList.remove('running-legs');
});

// Start loop
requestAnimationFrame(gameLoop);
